export const config = {
  baseUrl: "http://localhost:4000", //"https://seedonline.org",,"https://udyamit.in"
  register: "/api/reg",
  personal: "/api/personal",
  address: "/api/address",
  qulification: "/api/qulification",
  prefrance: "/api/prefrance",
  document: "/api/document",
  upload: "/upload",
  pay: "/pay",
  subscription: "/api/subscription",
  job: "/api/job",
  jobs: "/api/jobs",
  jobsByEmail: "/api/getJobsByEmail",
  digital: "/api/digital",
  digitals: "/api/digitals",
  checkApplyStatus: "/api/checkApplyStatus",
  news: "/api/news",
  getAllNews: "/api/getAllNews",
};
